[package]
name = "arduino"
version.workspace = true
edition.workspace = true


# [dependencies]
# project1-protocol = { path = "../protocol" }
# arduino-hal = { git = "https://github.com/rahix/avr-hal", features = ["arduino-uno"] }
# panic-halt = "1"

# [profile.release]
# opt-level = "s"
# lto = true
# codegen-units = 1
# panic = "abort"
